apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: redis-volume
  namespace: kube-honduras
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{STORAGE_CLASS_NAME}}
